version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sentryx_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: sentryx_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/sentryx
      - PORT=5000
    depends_on:
      - mongodb

volumes:
  mongo_data: